<?php
// +----------------------------------------------------------------------
// | 自定义配置
// +----------------------------------------------------------------------
// | Copyright (c) 2018 http://www.jeoshi.com All rights reserved.
// +----------------------------------------------------------------------
// | Author: kevin
// +----------------------------------------------------------------------

return [
    // 项目名称
    'name'             => '报表中心',
    'apppath'          => '/count/',
    // sku 开发图片域名
    'erpdomain'        => 'http://erp.spocoo.com',
    // sku 开发图片小图
    'sku_minimg'       => '/images/small/',
    // 所有平台名称
    'platforms'        => ['ebay', 'aliexpress', 'wish', 'amazon', 'cdiscount', 'priceminister', 'walmart', 'joom', 'linio', 'lazada', 'shopee', 'jumia', 'fnac', 'manomano', 'mymall', 'wadi'],
    // ERP订单类型转换
    'erpordertype'     => ['' => 0, -1 => 0, 0 => 0, 1 => 1, 2 => 2, 3 => 3, 4 => 4, 5 => 5, 6 => 6, 7 => 7, '线下订单' => 6, '补发订单' => 3, 8 => 8],
    // 订单类型 0=原始订单 1=合并订单 2=拆分订单 3=补发订单 4=退款订单 5=手工订单 6=线下订单 7=退货订单
    'ordertype'        => ['0' => '原始订单', '1' => '合并订单', '2' => '拆分订单', '3' => '补发订单', '4' => '退款订单', '5' => '手工订单', '6' => '线下订单', '7' => '不发订单', '8' => '礼物订单'],
    // 进入回收站原因
    'recyclereason'    => ['系统', '缺货订单', 'sku淘汰/停产', '渠道不支持', '负利润', '客户信息有误', '客户取消', '巴西订单', '补差额订单', '超时不发', 'sku/运费/价格设置错误', '黑名单', 'shopee订单超重/金额过大', '订单无法清关', '刷单订单', '测试订单', '其它'],
    // 提示语，可调整
    'tips'             => '统计数据存在一定的延迟性, 请勿与订单实时对比.',
    // 订单状态
    'orderstatus'      => [
        // 100  => '全部',
        0    => '未付款',
        1    => '待处理',
        1722 => '等待分配',
        1723 => '物流交运',
        1733 => '待查面单',
        1977 => '待入WMS',
        1964 => '已入WMS',
        1724 => '等待扫描',
        2009 => '已出库待称重',
        2    => '已经发货',
        1731 => '回收站',
        2018 => '订单拦截',
        1725 => '缺货订单',
        1728 => '有问题订单',
        2017 => '不发货订单',
        1738 => '负利润订单',
        1988 => '虚拟仓订单',
        1987 => '不包邮订单',
    ],
    // 费用字段
    'order_fee_fields' => [
        'total'                  => '总金额',
        'cost'                   => '商品成本',
        'shipfee'                => '客户付的运费',
        'estimate_profit'        => '预估利润',
        'estimate_profit_margin' => '预估利润率/1000',
        'profit'                 => '真实利润',
        'profit_margin'          => '真实利润率/1000',
        'package_fee'            => '包材费',
        'platform_fee'           => '平台费',
        'paypal_fee'             => 'paypal费',
        'onlinefee'              => '线上运费/尾程费',
        'otherfee'               => '其他费用(备用)',
        'brokerage_fee'          => '佣金',
        'refund_money'           => '退款金额',
        'return_money'           => '退货金额',
        'order_weight'           => '电子称重(KG)',
        'order_freight'          => '计算运费(￥)',
        'carrier_weight'         => '物流称重(KG)',
        'carrier_freight'        => '物流运费(￥)',
    ],

    // 导出订单字段
    'order_fields'     => [
        'id'                     => '系统订单号',
        'recordnumber'           => '平台订单号',
        'platform'               => '平台',
        'platform_account'       => '平台账号',
        'platform_account_id'    => '平台帐号ID',
        'type'                   => '订单类型',
        'couny'                  => '国家二字码',
        'couny_name'             => '国家名称',
        'city'                   => '城市',
        'state'                  => '洲',
        'total'                  => '总金额',
        'cost'                   => '商品成本',
        //'rates'                  => '相对美元的汇率',
        'currency'               => '币种',
        'shipfee'                => '客户付的运费',
        'estimate_profit'        => '预估利润',
        'estimate_profit_margin' => '预估利润率/1000',
        'profit'                 => '真实利润',
        'profit_margin'          => '真实利润率/1000',
        'profit_status'          => '是否确认利润',
        'package_fee'            => '包材费',
        'platform_fee'           => '平台费',
        'paypal_fee'             => 'paypal费',
        'onlinefee'              => '线上运费/尾程费',
        'otherfee'               => '其他费用(备用)',
        'brokerage_fee'          => '佣金',
        'refund_money'           => '退款金额',
        'return_money'           => '退货金额',
        //'gross_profit'           => '毛利',
        'carrier'                => '物流渠道',
        'carrier_company'        => '物流公司',
        'tracknumber'            => '跟踪号',
        'store_id'               => '仓库',
        'location'               => 'Location',
        'order_weight'           => '电子称重(KG)',
        'order_freight'          => '计算运费(￥)',
        'carrier_weight'         => '物流称重(KG)',
        'carrier_freight'        => '物流运费(￥)',
        'sales_branch_id'        => '销售人员所在组织架构',
        'sales_user'             => '销售人员',
        'stock_user'             => '采购人员',
        'develop_user'           => '开发人员',
        'status'                 => '状态',
        'createdtime'            => '进系统时间',
        'paidtime'               => '付款时间',
        'deliverytime'           => '发货时间',
        'refund_time'            => '退款时间',
        'return_time'            => '退货时间',
        'recycle_time'           => '进回收站时间',
        'profit_time'            => '确认利润时间',
        'recycle_reason'         => '进回收站原因',
        'uptime'                 => '订单更新时间',
    ],

    'sku_fields' => [
        // 'order_id'            => '订单ID',
        // 'platform'            => '平台',
        // 'platform_account'    => '平台账号',
        // 'platform_account_id' => '平台帐号ID',
        'sku'             => 'SKU编号',
        // 'location'            => '发货地(ebay使用)',
        // 'store_id'            => '仓库',
        'total'           => '总金额',
        'cost'            => '物品成本',
        'pack_cost'       => '包材成本',
        //'package_fee'     => '包材费',
        'platform_fee'    => '转换费',
        'paypal_fee'      => 'paypal费',
        'onlinefee'       => '线上运费/尾程费',
        'otherfee'        => '其他费用(备用)',
        'brokerage_fee'   => '佣金/成缴费/平台费',
        'freight'         => 'SKU' . '实际运费',
        'profit'          => 'SKU' . '利润',
        'sales_label'     => 'SKU' . '销售标签',
        'sales_user'      => 'SKU' . '销售人员',
        'sales_branch_id' => 'SKU' . '销售人员所在部门ID',
        'stock_user'      => 'SKU' . '采购人员',
        'develop_user'    => 'SKU' . '开发人员',
        'develop_time'    => 'SKU' . '开发时间',
        'instore_time'    => 'SKU' . '首次入库时间',
        'uptime'          => 'SKU' . '更新时间',
    ],
];
